### ISSUE TITLE
Add PHPStan

### ISSUE THREAD

**Issue by kubk** [riverwaysoft/dto-converter#11]

**Comment by mitalcoi** [comment]
https://github.com/riverwaysoft/dto-converter/commit/47e99390edaad5158bae4f5b977f4cc205fa52c1

**Comment by mitalcoi** [comment]
https://github.com/riverwaysoft/dto-converter/actions/runs/1132263847

**Comment by kubk** [comment]
@mitalcoi Thanks, I'll resolve them
